name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Expo & dependencies
        run: |
          npm install -g expo
          npm ci

      - name: Add expo-dev-client
        run: npx expo install expo-dev-client

      - name: Prebuild and Install CocoaPods
        run: |
          npx expo prebuild --platform ios --clean
          cd ios
          pod install

      - name: Build iOS archive (unsigned)
        run: |
          RAW_NAME=$(jq -r .name package.json)

          xcodebuild \
            -workspace ios/$RAW_NAME.xcworkspace \
            -scheme $RAW_NAME \
            -configuration Debug clean archive \
            -sdk iphoneos \
            -archivePath build/$RAW_NAME.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export IPA
        run: |
          RAW_NAME=$(jq -r .name package.json)

          cd build/$RAW_NAME.xcarchive/Products/Applications
          mkdir -p Payload
          cp -r $RAW_NAME.app Payload/
          zip -r $$RAW_NAME.ipa Payload
          mv $$RAW_NAME.ipa $GITHUB_WORKSPACE/

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: $RAW_NAME-ios-onsign
          path: ios/$RAW_NAME.ipa
